### ISSUE TITLE
[Suggestion] Separate Menu Templates

### ISSUE THREAD

**Issue by echoless3484** [Maaack/Godot-Game-Template#102]
Hey there, I thought about some things and realized some people might not want all of the Menus Template, but it may be difficult to separate, so maybe separating the menus into their individual scenes like "Main Menu Template", "Settings Menu Template", "Pause Menu Template", and so on could be beneficial to those users, and make it more accessible and modular.

**Comment by Maaack** [comment]
I split Options Menus into a branch [test-options-menus ](https://github.com/Maaack/Godot-Game-Template/tree/test-options-menus) and added it to the Godot Asset Library as a release candidate version. If it works and fills the need intended, then I may split it into its own repo, as well.
![image](https://github.com/Maaack/Godot-Game-Template/assets/788630/58ef751f-0833-4384-9da6-cac2b428f290)
https://godotengine.org/asset-library/asset/3058

**Comment by Maaack** [comment]
Options Menus are available under their own repo and plugin now:
https://github.com/Maaack/Godot-Options-Menus
