### ISSUE TITLE
Pause menu isnt opening

### ISSUE THREAD

**Issue by aftrosrs** [Maaack/Godot-Game-Template#108]
https://github.com/Maaack/Godot-Menus-Template/issues/15
Bringing this here since this is where you get the pause menu.

No errors appear, it just doesn't open the pause menu when pressing ESC.
![image](https://github.com/Maaack/Godot-Game-Template/assets/112984970/2d008ef8-6a65-4782-ad71-8995178d1aa4)

**Comment by aftrosrs** [comment]
![image](https://github.com/Maaack/Godot-Game-Template/assets/112984970/d3d83139-4d56-4a85-80fc-c607b22ffb0f)
now when just trying to relaunch the project this shows up..

**Comment by aftrosrs** [comment]
> [Maaack/Godot-Menus-Template#15](https://github.com/Maaack/Godot-Menus-Template/issues/15) Bringing this here since this is where you get the pause menu.
> 
> No errors appear, it just doesn't open the pause menu when pressing ESC. ![image](https://private-user-images.githubusercontent.com/112984970/340143738-2d008ef8-6a65-4782-ad71-8995178d1aa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1ODMxNTEsIm5iZiI6MTcxODU4Mjg1MSwicGF0aCI6Ii8xMTI5ODQ5NzAvMzQwMTQzNzM4LTJkMDA4ZWY4LTZhNjUtNDc4Mi1hZDcxLTg5OTUxNzhkMWFhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwMDA3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzZlY2Y1YmU5OWY4MzNiNzA2Yjg3YWJhZjE5MGIzY2EzMjA0MjY4MTAxMjdiYTAyODgxODMxMmM3YTkwMjRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IQZsg9DlQ7JIpuMHh3spHfoXPC6g6TjtlwSk_QMH8-k)

This includes having fresh installed the plugin 30 times thus far and following the instructions. This is really disheartening, and im likely just gonna have to either make my own or find another plugin if you cant help me figure it out.

**Comment by Maaack** [comment]
I opened a new project and tested it. Pause menu worked in-game by  pressing `Esc`. No further setup was required. On my default Godot project, `Esc` is already bound to the built-in action `ui_cancel`.

The screenshot you provided of a keybinding isn't required. The other error appears for me sometimes when I open Godot, but not when I run the app. Let me know if that is not the case for you.

> im likely just gonna have to either make my own or find another plugin if you cant help me figure it out.

You are welcome to. I can improve documentation and fix bugs, but I'm not here for coaching during my weekend time.

If you can provide some further details of what you have tried, I can try to figure out where the misunderstanding is and improve the documentation.

**Comment by aftrosrs** [comment]
I dont know what more you want me to say, i literally used a fresh install from the godot launcher to create a project, changing nothing but the paths needed to direct the opening to the main menu, main menu to the world file i selected. i get all the way to this point. and esc still does nothing.

**Comment by Maaack** [comment]
> I dont know what more you want me to say...
Yet everything you said after was more helpful than what was said before. Next time opening an issue, please lead with that.

The documentation doesn't go this far into setting up custom game scenes, yet. Things like win/lose screens, pause menu, level advancement, etc. need to be explicitly added or connected.

I recommend opening up any `GameUI.tscn` that came with the addon, copying the `PauseMenuController` node in the scene tree, opening up your custom game scene, and pasting the node into it.
