### ISSUE TITLE
Credits don't scroll the second time

### ISSUE THREAD

**Issue by Taylor-Mattison** [Maaack/Godot-Game-Template#114]
Steps to reproduce:

1. Create a new project and install Godot-Game-Template from the Godot AssetLib
2. Enable Godot-Game-Template plugin and restart Godot
3. Run the project and click the Credits button in the main menu, allow the credits to scroll all the way through and automatically return to the main menu
4. Click the credits button again

Expected behavior: The credits should scroll through again
Actual behavior: The credits do not start scrolling and show a blank screen until you scroll down

**Comment by Taylor-Mattison** [comment]
Thanks for the quick fix!

**Comment by Maaack** [comment]
Ha, I won't always be that quick; this was good timing.

Thanks for the detailed bug report!
