### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by juliusspeak** [Maaack/Godot-Game-Template#127]
E 0:00:13:0559   SceneLoader.gd:47 @ change_scene_to_resource(): Can't create buffer of size: 0, error -3.
  Condition "err" is true. Returning: ERR_CANT_CREATE
  drivers/vulkan/rendering_device_vulkan.cpp:1378 @ _buffer_allocate()
  SceneLoader.gd:47 @ change_scene_to_resource()

![ 2024-08-02 045433](https://github.com/user-attachments/assets/dede1754-83c3-409c-8e95-9c48018cd422)

**Comment by Maaack** [comment]
Sorry you are having issues. Please include the steps you took to reproduce the bug.

**Comment by juliusspeak** [comment]
I can't repeat it, I changed a lot of things :(

Let me clarify - everything works, but there are errors in the log. And only in forward mode. In compatibility mode I get other errors:
![img](https://github.com/user-attachments/assets/87520c34-db79-4db5-bac8-88c3f9eb6f82)
