### ISSUE TITLE
Comply with recommended directory- and file-names

### ISSUE THREAD

**Issue by Motioneer** [Maaack/Godot-Game-Template#135]
The Godot documentation recommends [the use snake_case for folder and file names,](https://docs.godotengine.org/en/stable/tutorials/best_practices/project_organization.html) to avoid problems with case insensitive file systems.
I'm currently manually renaming all files in my project, since the addon files get inherited by the implementations, I am renaming these too. 
I wonder if it would be a good idea to change them in the source as well.
Thank you for this great template!

**Comment by Maaack** [comment]
Thanks for linking the documentation. I was bugged by the fact that they aren't consistent between the C# files and GDScript, but seeing that point acknowledged in the docs makes me feel better about it. It appears to have at least been weighed as a factor before making the style guide decisions.

**Comment by Motioneer** [comment]
Oh wow, that was a quick turnaround. I actually wanted to create a pull request, but you beat me to it.
Amazing work!
