### ISSUE TITLE
Input Issue w/ Animated Main Menu 

### ISSUE THREAD

**Issue by gbillus** [Maaack/Godot-Game-Template#146]
I apologize if this is spamming you. I am new to Github and just want to make sure you got notified. I begin this topic in a issue that I just noticed was closed. I have resolved the issue locally and have committed the change that fixed it to my projects repo. I got a theory that theres some sort of bug that is partially triggered by the UI scale that you chose. Moving it seemed to have resolved the bug. I invited you to my projects repo in case it may be of use to you. Once again, Thank you providing these templates to the community. I hope that my discovery will help resolve the issue for everyone.

##################################################################

             Okay so I have news. I accidently fixed the issue, im not sure how. But more importantly, I committed to my repo before and after. I have the settings committed that would be necessary for a control group, to preform more granular tests for finer data on the issue... at least on my machine which was effected in the first place. I'm just taking a guess in the dark, but I moved the UI scaling slightly so it wouldn't overlap my background image. When I went to test my work, I loaded the animated scene by mistake and discovered that the input bug was somehow resolved. I could share the repo with you if it would be any use. I can also preform tests on builds if you lay out the instructions for me.

_Originally posted by @gbillus in https://github.com/Maaack/Godot-Game-Template/issues/110#issuecomment-2347858264_

**Comment by Maaack** [comment]
I've reopened https://github.com/Maaack/Godot-Game-Template/issues/110 . Since that issue has most of the conversation, I will mark this as a duplicate and close it.

Thank you.
