### ISSUE TITLE
Pause menu documention addition or boolean option

### ISSUE THREAD

**Issue by catprisbrey** [Maaack/Godot-Game-Template#177]
First, I want to state just how impressive this project is. Using it for the first time on a large, currently existing project and I expected a lot of pain points, and I am blown away by how easy this is to implement. 

That said, it also led to a small confusions that might be able to be improved with simple documentation, or an addition of a bool to the pause menu code.

It wasn't apparent In the documentation that I could simply turn on the bool to pause the game while the pause menu was present. I ended up punching in some crude additions to add pause in code before I realized you already had that built in. A small note in the documentation could assist there.

Another issue I had that could be fixed with documentation or a bool  might be with how it grabs Focus. When I first used the pause menu, I couldn't use UI up or down to cycle through the options. I poured through my code to see if other UI elements were grabbing Focus or swallowing input, or if the issue was elsewhere. I eventually saw the pause menu detects if joypad is being used and that determines whether it grabs Focus on the first menu item or not. 

For my game, joypad or not, I have the cursor hidden and mouse captured. A small note in the documentation that the pause menu does this detection, or even adding a bool enable "first item focus" could be really helpful for people with similar setups.

That's all, and these are sort of non-issue issues. There are no bugs, your code is great. These are just more documentation or quality of life improvements.Thanks!

**Comment by Maaack** [comment]
Yay! I'm really glad you found it easy to plug into your pre-existing, large project.

I appreciate you sharing your pain points and suggestions. I'll try including these in the next update.

Thanks for all the feedback and support!
