### ISSUE TITLE
How to add audio ? 

### ISSUE THREAD

**Issue by Zifai** [Maaack/Godot-Game-Template#44]

**Comment by Maaack** [comment]
In the [Existing Project Instructions](https://github.com/Maaack/Godot-Game-Template/blob/main/addons/maaacks_game_template/docs/ExistingProject.md), Step 6 covers adding audio to the UI. 

> By scene.
> 1. Open MainMenu.tscn and PauseMenu.tscn.
> 2. Select the UISoundController node.
> 3. Add audio streams to the various UI node events.
> 4. Save the scenes.

> Project-wide, with extras/.
> 1. Go to Project > Project Settings… > Autoload.
> 2. Make sure UISoundControllerAutoload is listed.
> 3. Note: It does not need a global variable enabled.
> 4. Close the window.
> 5. Open UISoundControllerAutoload.tscn.
> 6. Select the UISoundController node.
> 7. Add audio streams to the various UI node events.
> 8. Save the scene.

Let me know if any of those instructions are unclear, or if you are referring to something else, like background music?

**Comment by Maaack** [comment]
I added the following instructions:

>     1.  Add `Music` and `SFX` to the project's default audio busses.
> 
>         1.  Open the Audio bus editor.
>         2.  Click the button "Add Bus" twice (x2).
>         3.  Name the two new busses `Music` and `SFX`.
>         4.  Save the project.
