### ISSUE TITLE
Menu navigation is possible via directional input during title/sub-title fade animation, causing other buttons than Play to be focused when buttons appear

### ISSUE THREAD

**Issue by hsandt** [Maaack/Godot-Game-Template#72]
Setting Game Scene Path allows to show Play button, but sometimes the Options button is still the one focused on start, instead of the expected Play button at the top.

EDIT: found cause: ghost navigation, see comment below

Btw nice addon, it goes farther than EasyMenus and already has Credits and above all, remappable controls! I'll use it from now on for my jams, and maybe even my other games!

**Comment by hsandt** [comment]
Sorry, wrong bug description. In fact, Play is really focused on start, but I can ghost select other buttons by pressing directional input during the title animation. Pressing down once during title fade in will select Options just below. Twice, Credits.

So the issue is that navigation is allowed while buttons are invisible.

**Comment by hsandt** [comment]
Similarly, it's possible to ui_accept a button and directly enter e.g. the Options during the title fade in, by pressing Enter.

**Comment by Maaack** [comment]
That's unintended behavior. I think player's would probably be more accustomed to the selection occurring after the buttons are fully faded-in. Being able to navigate to the options during the fade is also outright silly.

Thanks for reporting and the update :slightly_smiling_face:

**Comment by hsandt** [comment]
A side effect of this is that when entering Options this way, user is unable to click on the buttons except Back, at which point user can reenter Options to properly interact with the sub-menu.

It may be related to some canvas layer or interaction flag not set properly as the animation was interrupted.

However, it should be fixed along this bug. Forcing fade animation end by pressing Space or Enter, just as when you click, should solve the issue.

**Comment by hsandt** [comment]
Thx, looks like Godot Asset Library still shows 0.7.0 so I'll have to install the release from GitHub manually.

**Comment by Maaack** [comment]
Thanks for confirming the fix. Sorry for the trouble with the menu's template being on an older version. I finished a jam and should have more time to sync the templates. Eventually I hope to find some way to automate that.
