### ISSUE TITLE
Suggestion: Simplifying the process of propagating changes to the other repos

### ISSUE THREAD

**Issue by Maaack** [Maaack/Godot-Game-Template#90]
These are the other repos that this repo shares code with:

- https://github.com/Maaack/Godot-Menus-Template
  -   https://github.com/Maaack/Godot-Credits-Scene
  -   https://github.com/Maaack/Godot-Music-Controller
  -   https://github.com/Maaack/Godot-UI-Sound-Controller
  -   https://github.com/Maaack/Godot-Scene-Loader

It would be a huge time-saver if some of the process of porting the code could be automated. It could be done from either end, going up the chain, or down, and still save time. The major differences between repos are the plugin directory name and the scope of their contents.

**Comment by Maaack** [comment]
I've since added another to the list.
* https://github.com/Maaack/Godot-Options-Menus

The manual process is time-consuming and error prone. I'm sure there's software that would do this automatically, or I could write a script. Any outside support would be appreciated.

**Comment by gbillus** [comment]
If your projects were in separate folders in your monorepo, then you could use SubRepo as an alternative to submodules and subtrees. By default, it squashes the commits so it wont clutter you main repo. It will commit the files from the subrepo, in the current state you have the subrepo in, to the main repo it inhabits. No weird submodule build scripts to run after a fresh clone

**Comment by Maaack** [comment]
> If your projects were in separate folders in your monorepo, then you could use SubRepo as an alternative to submodules and subtrees.

Thanks for the recommendation! I looked into SubRepo a little bit. I don't currently have my project setup in a way that I think I could immediately take advantage of it, but it's good to know the option is there.

**Comment by Maaack** [comment]
To add a little more context, I want to make a set of files bulk update their contents from another set of files.

I need a little more flexibility than is provided by a hard link, as I will need to change some of the contents after copying (mostly paths from `game_template` -> `menus_template`). Copy+pasting the entire directory results in adding many files to the other repos that aren't wanted, and then need to be trimmed out. Something like a  Copy+ReplaceOnly feature might be enough.

I don't mind if this is a script I need to run in each of the shared repos, either. That would still be less manual labor than it is now.
